name: uploadcare_client

packages:
  - uploadcare_client
  - uploadcare_flutter
  - uploadcare_flutter_example
  - uploadcare_server_mock

ide:
  intellij: false

command:
  version:
    workspaceChangelog: false
    linkToCommits: false
    branch: master
    hooks:
      preCommit: |
        melos run pubspec:gen
        melos run test
  bootstrap:
    hooks:
      post: |
        melos run mock_file:gen

scripts:
  pubspec:gen:
    run: |
      melos exec -c 1 --scope="*uploadcare_client*" -- \
        dart run pubspec_extract --filter="name,version" -d "lib/src/pubspec.dart"

  analyze:
    run: |
      melos exec -c 1 -- \
        dart analyze .
    description: |
      Run `dart analyze` in all packages.

  format:
    run: |
      melos exec -c 1 -- \
        dart format .
    description: |
      Run `dart format` in all packages

  test:
    run: |
      ./tool/test.sh

  mock_file:gen:
    run: |
      ./tool/generate_bin_assets.sh
