name: uploadcare_client
description: A flutter library for working with Uploadcare REST API. File uploads, media processing, and adaptive delivery for web and mobile.
version: 2.1.0
homepage: https://github.com/KonstantinKai/uploadcare_client
repository: https://github.com/KonstantinKai/uploadcare_client
issue_tracker: https://github.com/KonstantinKai/uploadcare_client/issues

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  crypto: ^2.1.3
  meta: ^1.1.8
  mime_type: ^0.3.0
  http_parser: ^3.1.4
  equatable: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.3
  dotenv: ^1.0.0
  mockito: ^4.1.1