name: uploadcare_server_mock
description: A server app using the shelf package and Docker.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  path: ^1.8.2
  uuid: ^3.0.6
  shelf_multipart: ^1.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
